# Generated by Django 4.0 on 2021-12-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_left',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
