# Generated by Django 4.0 on 2021-12-18 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_manufacturerorder_manufacturer_and_more'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Accounts.myuser'),
        ),
    ]
