# Generated by Django 4.0 on 2021-12-19 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='buisness_type',
        ),
    ]
