# Generated by Django 4.0 on 2021-12-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_remove_manufacturer_buisness_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='certification',
        ),
    ]
