# Generated by Django 4.0 on 2021-12-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_manufacturer_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='total_employee',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='year_esatblished',
            field=models.CharField(max_length=255),
        ),
    ]
