# Generated by Django 4.0 on 2021-12-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='token',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='token',
            field=models.IntegerField(default=5),
        ),
    ]
