# Generated by Django 4.0 on 2021-12-18 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_company_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='token',
        ),
        migrations.AddField(
            model_name='company',
            name='users_id',
            field=models.IntegerField(default=2),
        ),
    ]
