# Generated by Django 4.0 on 2021-12-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_manufacturerorder_manufacturer_and_more'),
        ('clients', '0006_remove_company_token_company_users_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='users_id',
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Accounts.myuser'),
        ),
    ]
