# Generated by Django 4.0 on 2021-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_company_users_id_alter_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='patwat@gmail.com', max_length=255),
        ),
    ]
