# Generated by Django 4.0 on 2021-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_remove_company_user_company_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='token',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(default='patwat@gmail.com', max_length=255),
        ),
    ]
