# Generated by Django 4.0 on 2021-12-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_manufacturer_token_manufacturer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturerorder',
            name='lowerLimit',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='upperLimit',
            field=models.IntegerField(default=500),
        ),
    ]
