# Generated by Django 4.0 on 2021-12-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_manufacturerorder_lowerlimit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='manufacturerorder',
            name='dispersion_duration',
        ),
        migrations.AddField(
            model_name='manufacturerorder',
            name='last_date_dispersion',
            field=models.DateField(default=None),
        ),
    ]
