# Generated by Django 4.0 on 2021-12-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='type',
            field=models.CharField(default='Manufacturer', max_length=20),
        ),
    ]
