# Generated by Django 4.0 on 2021-12-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_myuser_email_is_verified_myuser_phone_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='email_otp',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
