# Generated by Django 4.0 on 2021-12-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_myuser_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='phone_otp',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
