# Generated by Django 4.0 on 2021-12-19 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_remove_manufacturerorder_manufacturer_and_more'),
        ('Accounts', '0006_alter_myuser_is_active'),
    ]

    operations = [
    ]
